### ISSUE TITLE
[Bug?]: backdrop-filter moves ha-list several 100px to the right

### ISSUE THREAD

**Issue by derMicro** [thomasloven/lovelace-card-mod#560]
### My Home Assistant Version

Home Assistant OS
Core: 2025.12.3
Supervisor: 2025.12.3
Operating System: 16.3
Frontend: 20251203.2
card-mod:latest

### My lovelace configuration method

YAML

### What I am doing

I regularly use card-mod for individual HA cards and the backdrop filter in the themes file.

### What I expect to happen

The drop-down menu of the Select tile does not move

### What happened instead

When I use any backdrop filter in the themes file, the drop-down menu shifts. However, I can't say when this started happening, as I only noticed it when I was creating a dashboard on Android. This doesn't happen on our iPads with iOS when using the webkit backdrop filter. The position of the drop-down menu is correct there. The error also occurs on a PC in Edge. Except for backdrop-filter: none and backdrop-filter: unset, all options are affected by the error.

### Minimal steps to reproduce

1. use a theme-file
2. create a dashboard with tile (use a select entity)
2. put follow Code in your theme-file

```
doogee_dashboard_v1:

  card-mod-theme: "doogee_dashboard_v1"
  card-mod-card: |
    ha-card {
      backdrop-filter: blur(10px);
    }
```

<img width="1120" height="539" alt="Image" src="https://github.com/user-attachments/assets/7b66abb4-6b7f-49fe-a22d-21f0566dfc52" />

3. repeat with 
```
doogee_dashboard_v1:

  card-mod-theme: "doogee_dashboard_v1"
  card-mod-card: |
    ha-card {
      backdrop-filter: none;
    }
```
and reload theme, the menu move back to correct position

<img width="718" height="502" alt="Image" src="https://github.com/user-attachments/assets/56737103-566c-40de-ba23-48836f1e4709" />

...

### Include any yaml code here

```YAML
doogee_dashboard_v1:

  card-mod-theme: "doogee_dashboard_v1"
  card-mod-card: |
    ha-card {
      backdrop-filter: blur(10px);
    }

  background-image: "center / cover no-repeat fixed url('/local/_my/wallpapers/doogee_v1.png')"
  lovelace-background: var(--background-image)

  masonry-view-card-margin: 4px 4px 4px
  
  primary-color: rgba(85, 175, 255, 1)
  accent-color: rgba(85, 175, 255, 1)
  disabled-color: var(--grey-color)

  ha-card-border-radius: 4px
  ha-card-background: rgba(17, 37, 79, 0.2)
  ha-card-border-width: 2px
  ha-card-textalign: center
  state-icon-color: rgba(255, 255, 255, 1)
  border-color: rgba(255, 255, 255, 1)
  switch-checked-color: var(--accent-color)
  switch-checked-track-color: var(--accent-color)
  switch-checked-button-color: rgba(255, 255, 255, 1)

  more-info-header-background: var(--accent-color)
  paper-dialog-background-color: var(--accent-color)
  popup-border-radius: var(ha-card-border-width)

  wa-color-brand-fill-normal: rgba(85, 175, 255, 1)
  wa-color-brand-border-normal: var(--accent-color)
  wa-color-brand-on-normal: var(--accent-color)
  wa-color-brand-fill-loud: var(--accent-color)

  ha-color-fill-primary-normal-hover: rgba(48, 93, 133, 1)
  ha-color-fill-primary-loud-hover: rgba(48, 93, 133, 1)

  state-active-color: var(--accent-color)
  state-inactive-color: rgba(128, 128, 128, 0.7)
  state-unavailable-color: rgba(128, 128, 128, 0.4)

  state-red-color: rgba(255, 60, 30, 1)
  state-green-color: rgba(0, 200, 100, 1)
  state-orange-color: rgba(220, 160, 70, 1)

  state-alarm_control_panel-armed_away-color: 'var(--state-green-color)'
  state-alarm_control_panel-armed_custom_bypass-color: 'var(--state-green-color)'
  state-alarm_control_panel-armed_home-color: 'var(--state-green-color)'
  state-alarm_control_panel-armed_night-color: 'var(--state-green-color)'
  state-alarm_control_panel-armed_vacation-color: 'var(--state-green-color)'
  state-alarm_control_panel-arming-color: 'var(--state-orange-color)'
  state-alarm_control_panel-disarming-color: 'var(--state-orange-color)'
  state-alarm_control_panel-pending-color: 'var(--state-orange-color)'
  state-alarm_control_panel-triggered-color: 'var(--state-red-color)'
  state-alert-off-color: var(--paper-item-icon-color)
  state-alert-on-color: 'var(--state-red-color)'
  state-automation-active-color: 'var(--accent-color)'
  state-binary_sensor-active-color: 'var(--accent-color)'
  state-binary_sensor-battery-on-color: 'var(--state-red-color)'
  state-binary_sensor-carbon_monoxide-on-color: 'var(--state-red-color)'
  state-binary_sensor-gas-on-color: 'var(--state-red-color)'
  state-binary_sensor-heat-on-color: 'var(--state-red-color)'
  state-binary_sensor-lock-on-color: 'var(--state-red-color)'
  state-binary_sensor-moisture-on-color: 'var(--state-red-color)'
  state-binary_sensor-problem-on-color: var(--state-red-color)
  state-binary_sensor-safety-on-color: 'var(--state-red-color)'
  state-binary_sensor-smoke-on-color: 'var(--state-red-color)'
  state-binary_sensor-sound-on-color: 'var(--state-red-color)'
  state-binary_sensor-tamper-on-color: 'var(--state-red-color)'
  state-climate-auto-color: 'var(--accent-color)'
  state-climate-cool-color: 'var(--accent-color)'
  state-climate-dry-color: 'var(--accent-color)'
  state-climate-fan_only-color: 'var(--accent-color)'
  state-climate-heat-color: 'var(--state-orange-color)'
  state-climate-heat-cool-color: 'var(--accent-color)'
  state-cover-active-color: 'var(--accent-color)'
  state-device_tracker-active-color: 'var(--accent-color)'
  state-device_tracker-home-color: 'var(--accent-color)'
  state-fan-active-color: 'var(--accent-color)'
  state-group-active-color: 'var(--accent-color)'
  state-humidifier-active-color: 'var(--accent-color)'
  state-light-active-color: 'var(--accent-color)'
  state-lock-jammed-color: 'var(--state-red-color)'
  state-lock-locked-color: 'var(--accent-color)'
  state-lock-pending-color: 'var(--state-orange-color)'
  state-lock-unlocked-color: var(--paper-item-icon-color)
  state-media_player-active-color: 'var(--accent-color)'
  state-person-active-color: 'var(--accent-color)'
  state-person-home-color: 'var(--accent-color)'
  state-plant-active-color: 'var(--state-red-color)'
  state-siren-active-color: 'var(--state-red-color)'
  state-sun-above_horizon-color: 'var(--amber-color)'
  state-sun-below_horizon-color: 'var(--indigo-color)'
  state-switch-active-color: 'var(--accent-color)'
  state-update-active-color: 'var(--accent-color)'
  state-vacuum-active-color: 'var(--accent-color)'
  state-sensor-battery-high-color: 'var(--accent-color)'
  state-sensor-battery-low-color: 'var(--state-red-color)'
  state-sensor-battery-medium-color: 'var(--state-orange-color)'
```

### Error messages from the browser console

```console

```

### By checking each box below I indicate that I ...

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by dcapslock** [comment]
Hi, I am using a mushroom select to replicate with your config (Chrome on Mac). I also find that using theme variable `ha-card-backdrop-filter: blur(10px)` **without** card-mod loaded (removed entirely) also causes the same issue. So this is not a card-mod issue.

Also if I apply backdrop-filter to any mdc-select menu directly (e.g. in more-info for select) this issue shows as well. So not just a mushroom select issue.

I have seen strange positioning issues with the dropdown menu which is is a material design select menu, which tries to calculate menu surface position dynamically. 

I suggest to submit a Frontend issue that using the theme setting `ha-card-backdrop-filter: blur(10px)` causes the issue.

**Comment by dcapslock** [comment]
FYI: The issue will somehow be related to how backdrop-filter affects the BackdropRoot and how that affects the stacking context making the menu surface offset be relative to where the backdrop-filter is applied rather that the viewport.

See https://drafts.csswg.org/filter-effects-2/#BackdropRootTriggers

I have taken a look to see where a possible fix/workaround lies for Frontend but nothing found and as I have spent a few hours now I need to stop and allow those with better knowledge of the concepts and material design menu surface to work out.

**Comment by dcapslock** [comment]
Basically anything on the list in the link I shared ([BacdropRootTriggers](https://drafts.csswg.org/filter-effects-2/#BackdropRootTriggers)) may cause the issue. E.g. filter, opacity not 1 etc. It’s not acard_mod issue in any way.

**Comment by derMicro** [comment]
Hello,

On the one hand, it's good to know that card-mod isn't the problem, but on the other hand, it's bad for me because the search continues ;)

How can I use the filter in the themes file without needing card-mod? I think that if I report this to the frontend team, they will immediately say that card-mod is to blame if I show them the code from the current issue.

I had already considered whether it would be possible to override this somewhere in the hierarchy so that the filter does not apply to the drop-down menus, or whether the coordinates could be corrected with card-mod, but I am not familiar enough with the topic to locate the menu in the DCOM tree or address it accordingly.

**Comment by derMicro** [comment]
Workaround:

```
doogee_dashboard_v1:

  card-mod-theme: "doogee_dashboard_v1"
  card-mod-card: |
    ha-card {
      backdrop-filter: none;
      -webkit-backdrop-filter: none;
    }

    ha-card::before {
      content: '';
      position: absolute;
      inset: 0;
      backdrop-filter: var(--ha-card-backdrop-filter, blur(10px));
      -webkit-backdrop-filter: var(--ha-card-backdrop-filter, blur(10px));
      z-index: -1;
      pointer-events: none;
      );
    }
```
With this code adjustment, the drop-down menus remain in the correct position.
Nevertheless, thank you very much for your help and work in reproducing this :)

**Comment by dnestico** [comment]
This didn't fix mine unfortunatley

<img width="592" height="496" alt="Image" src="https://github.com/user-attachments/assets/68c43ef5-3705-4a33-a055-069970d1d06b" />

**Comment by dcapslock** [comment]
@dnestico FYI as noted in forums, this is not a card-mod issue.
